apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-app
  namespace: {{.Values.namespace}}
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      component: main-app
  template:
    metadata:
      labels:
        component: main-app
    spec:
      containers:
        - name: main-app
          image: {{.Values.image}}
          ports:
            - containerPort: 3000
          imagePullPolicy: {{.Values.imagePullPolicy}}
      imagePullSecrets:
        - name: regcred
