apiVersion: v1
kind: Service
metadata:
  name: dod-app
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
  selector:
    component: dod-app
