environment: default
namespace: effordia
domain: effordia.com
protocol: http
imageHub: ghcr.io/paramountric/effordia-hub
imageMain: ghcr.io/paramountric/effordia-main
imagePullPolicy: IfNotPresent
enableIngressTls: Disable
tlsSecretName: 'aws-lb-tls-is-use-so-this-is-skipped'
ingressClassName: public