apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: effordia-staging
  namespace: argocd
spec:
  description: Effordia project that runs in effordia.com
  sourceRepos:
    - '*'
  destinations:
    - namespace: effordia-staging
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
